name: star_wars
description: Simple example using graphql_flutter and graphql_codegen with
  Relay-like structure

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.0

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  graphql: ^5.1.2-beta.4
  graphql_flutter: ^5.1.1-beta.4
  provider: ^6.0.3

dev_dependencies:
  build_runner: ^2.2.0

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  graphql_codegen: ^0.11.0-beta.6

flutter:
  uses-material-design: true
